# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:07:44+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class AndroidInfo(BaseModel):
    androidFallbackLink: Optional[str] = Field(
        None, description='Link to open on Android if the app is not installed.'
    )
    androidLink: Optional[str] = Field(
        None,
        description='If specified, this overrides the ‘link’ parameter on Android.',
    )
    androidMinPackageVersionCode: Optional[str] = Field(
        None,
        description='Minimum version code for the Android app. If the installed app’s version code is lower, then the user is taken to the Play Store.',
    )
    androidPackageName: Optional[str] = Field(
        None, description='Android package name of the app.'
    )


class DesktopInfo(BaseModel):
    desktopFallbackLink: Optional[str] = Field(
        None, description='Link to open on desktop.'
    )


class DeviceInfo(BaseModel):
    deviceModelName: Optional[str] = Field(None, description='Device model name.')
    languageCode: Optional[str] = Field(
        None, description='Device language code setting.'
    )
    languageCodeFromWebview: Optional[str] = Field(
        None,
        description='Device language code setting obtained by executing JavaScript code in WebView.',
    )
    languageCodeRaw: Optional[str] = Field(
        None,
        description='Device language code raw setting. iOS does returns language code in different format than iOS WebView. For example WebView returns en_US, but iOS returns en-US. Field below will return raw value returned by iOS.',
    )
    screenResolutionHeight: Optional[str] = Field(
        None, description='Device display resolution height.'
    )
    screenResolutionWidth: Optional[str] = Field(
        None, description='Device display resolution width.'
    )
    timezone: Optional[str] = Field(None, description='Device timezone setting.')


class Event(Enum):
    DYNAMIC_LINK_EVENT_UNSPECIFIED = 'DYNAMIC_LINK_EVENT_UNSPECIFIED'
    CLICK = 'CLICK'
    REDIRECT = 'REDIRECT'
    APP_INSTALL = 'APP_INSTALL'
    APP_FIRST_OPEN = 'APP_FIRST_OPEN'
    APP_RE_OPEN = 'APP_RE_OPEN'


class Platform(Enum):
    DYNAMIC_LINK_PLATFORM_UNSPECIFIED = 'DYNAMIC_LINK_PLATFORM_UNSPECIFIED'
    ANDROID = 'ANDROID'
    IOS = 'IOS'
    DESKTOP = 'DESKTOP'
    OTHER = 'OTHER'


class DynamicLinkEventStat(BaseModel):
    count: Optional[str] = Field(
        None, description='The number of times this event occurred.'
    )
    event: Optional[Event] = Field(None, description='Link event.')
    platform: Optional[Platform] = Field(None, description='Requested platform.')


class DynamicLinkStats(BaseModel):
    linkEventStats: Optional[List[DynamicLinkEventStat]] = Field(
        None, description='Dynamic Link event stats.'
    )


class WarningCode(Enum):
    CODE_UNSPECIFIED = 'CODE_UNSPECIFIED'
    NOT_IN_PROJECT_ANDROID_PACKAGE_NAME = 'NOT_IN_PROJECT_ANDROID_PACKAGE_NAME'
    NOT_INTEGER_ANDROID_PACKAGE_MIN_VERSION = 'NOT_INTEGER_ANDROID_PACKAGE_MIN_VERSION'
    UNNECESSARY_ANDROID_PACKAGE_MIN_VERSION = 'UNNECESSARY_ANDROID_PACKAGE_MIN_VERSION'
    NOT_URI_ANDROID_LINK = 'NOT_URI_ANDROID_LINK'
    UNNECESSARY_ANDROID_LINK = 'UNNECESSARY_ANDROID_LINK'
    NOT_URI_ANDROID_FALLBACK_LINK = 'NOT_URI_ANDROID_FALLBACK_LINK'
    BAD_URI_SCHEME_ANDROID_FALLBACK_LINK = 'BAD_URI_SCHEME_ANDROID_FALLBACK_LINK'
    NOT_IN_PROJECT_IOS_BUNDLE_ID = 'NOT_IN_PROJECT_IOS_BUNDLE_ID'
    NOT_IN_PROJECT_IPAD_BUNDLE_ID = 'NOT_IN_PROJECT_IPAD_BUNDLE_ID'
    UNNECESSARY_IOS_URL_SCHEME = 'UNNECESSARY_IOS_URL_SCHEME'
    NOT_NUMERIC_IOS_APP_STORE_ID = 'NOT_NUMERIC_IOS_APP_STORE_ID'
    UNNECESSARY_IOS_APP_STORE_ID = 'UNNECESSARY_IOS_APP_STORE_ID'
    NOT_URI_IOS_FALLBACK_LINK = 'NOT_URI_IOS_FALLBACK_LINK'
    BAD_URI_SCHEME_IOS_FALLBACK_LINK = 'BAD_URI_SCHEME_IOS_FALLBACK_LINK'
    NOT_URI_IPAD_FALLBACK_LINK = 'NOT_URI_IPAD_FALLBACK_LINK'
    BAD_URI_SCHEME_IPAD_FALLBACK_LINK = 'BAD_URI_SCHEME_IPAD_FALLBACK_LINK'
    BAD_DEBUG_PARAM = 'BAD_DEBUG_PARAM'
    BAD_AD_PARAM = 'BAD_AD_PARAM'
    DEPRECATED_PARAM = 'DEPRECATED_PARAM'
    UNRECOGNIZED_PARAM = 'UNRECOGNIZED_PARAM'
    TOO_LONG_PARAM = 'TOO_LONG_PARAM'
    NOT_URI_SOCIAL_IMAGE_LINK = 'NOT_URI_SOCIAL_IMAGE_LINK'
    BAD_URI_SCHEME_SOCIAL_IMAGE_LINK = 'BAD_URI_SCHEME_SOCIAL_IMAGE_LINK'
    NOT_URI_SOCIAL_URL = 'NOT_URI_SOCIAL_URL'
    BAD_URI_SCHEME_SOCIAL_URL = 'BAD_URI_SCHEME_SOCIAL_URL'
    LINK_LENGTH_TOO_LONG = 'LINK_LENGTH_TOO_LONG'
    LINK_WITH_FRAGMENTS = 'LINK_WITH_FRAGMENTS'
    NOT_MATCHING_IOS_BUNDLE_ID_AND_STORE_ID = 'NOT_MATCHING_IOS_BUNDLE_ID_AND_STORE_ID'


class DynamicLinkWarning(BaseModel):
    warningCode: Optional[WarningCode] = Field(None, description='The warning code.')
    warningDocumentLink: Optional[str] = Field(
        None, description='The document describing the warning, and helps resolve.'
    )
    warningMessage: Optional[str] = Field(
        None,
        description='The warning message to help developers improve their requests.',
    )


class RetrievalMethod(Enum):
    UNKNOWN_PAYLOAD_RETRIEVAL_METHOD = 'UNKNOWN_PAYLOAD_RETRIEVAL_METHOD'
    IMPLICIT_WEAK_MATCH = 'IMPLICIT_WEAK_MATCH'
    EXPLICIT_WEAK_MATCH = 'EXPLICIT_WEAK_MATCH'
    EXPLICIT_STRONG_AFTER_WEAK_MATCH = 'EXPLICIT_STRONG_AFTER_WEAK_MATCH'


class VisualStyle(Enum):
    UNKNOWN_VISUAL_STYLE = 'UNKNOWN_VISUAL_STYLE'
    DEFAULT_STYLE = 'DEFAULT_STYLE'
    CUSTOM_STYLE = 'CUSTOM_STYLE'


class GetIosPostInstallAttributionRequest(BaseModel):
    appInstallationTime: Optional[str] = Field(
        None,
        description='App installation epoch time (https://en.wikipedia.org/wiki/Unix_time). This is a client signal for a more accurate weak match.',
    )
    bundleId: Optional[str] = Field(None, description='APP bundle ID.')
    device: Optional[DeviceInfo] = Field(None, description='Device information.')
    iosVersion: Optional[str] = Field(
        None, description='iOS version, ie: 9.3.5. Consider adding "build".'
    )
    retrievalMethod: Optional[RetrievalMethod] = Field(
        None,
        description='App post install attribution retrieval information. Disambiguates mechanism (iSDK or developer invoked) to retrieve payload from clicked link.',
    )
    sdkVersion: Optional[str] = Field(
        None,
        description='Google SDK version. Version takes the form "$major.$minor.$patch"',
    )
    uniqueMatchLinkToCheck: Optional[str] = Field(
        None,
        description='Possible unique matched link that server need to check before performing fingerprint match. If passed link is short server need to expand the link. If link is long server need to vslidate the link.',
    )
    visualStyle: Optional[VisualStyle] = Field(
        None,
        description='Strong match page information. Disambiguates between default UI and custom page to present when strong match succeeds/fails to find cookie.',
    )


class AttributionConfidence(Enum):
    UNKNOWN_ATTRIBUTION_CONFIDENCE = 'UNKNOWN_ATTRIBUTION_CONFIDENCE'
    WEAK = 'WEAK'
    DEFAULT = 'DEFAULT'
    UNIQUE = 'UNIQUE'


class RequestIpVersion(Enum):
    UNKNOWN_IP_VERSION = 'UNKNOWN_IP_VERSION'
    IP_V4 = 'IP_V4'
    IP_V6 = 'IP_V6'


class GetIosPostInstallAttributionResponse(BaseModel):
    appMinimumVersion: Optional[str] = Field(
        None,
        description='The minimum version for app, specified by dev through ?imv= parameter. Return to iSDK to allow app to evaluate if current version meets this.',
    )
    attributionConfidence: Optional[AttributionConfidence] = Field(
        None, description='The confidence of the returned attribution.'
    )
    deepLink: Optional[str] = Field(
        None,
        description='The deep-link attributed post-install via one of several techniques (fingerprint, copy unique).',
    )
    externalBrowserDestinationLink: Optional[str] = Field(
        None,
        description='User-agent specific custom-scheme URIs for iSDK to open. This will be set according to the user-agent tha the click was originally made in. There is no Safari-equivalent custom-scheme open URLs. ie: googlechrome://www.example.com ie: firefox://open-url?url=http://www.example.com ie: opera-http://example.com',
    )
    fallbackLink: Optional[str] = Field(
        None,
        description='The link to navigate to update the app if min version is not met. This is either (in order): 1) fallback link (from ?ifl= parameter, if specified by developer) or 2) AppStore URL (from ?isi= parameter, if specified), or 3) the payload link (from required link= parameter).',
    )
    invitationId: Optional[str] = Field(
        None,
        description='Invitation ID attributed post-install via one of several techniques (fingerprint, copy unique).',
    )
    isStrongMatchExecutable: Optional[bool] = Field(
        None,
        description='Instruction for iSDK to attemmpt to perform strong match. For instance, if browser does not support/allow cookie or outside of support browsers, this will be false.',
    )
    matchMessage: Optional[str] = Field(
        None,
        description='Describes why match failed, ie: "discarded due to low confidence". This message will be publicly visible.',
    )
    requestIpVersion: Optional[RequestIpVersion] = Field(
        None, description='Which IP version the request was made from.'
    )
    requestedLink: Optional[str] = Field(
        None,
        description='Entire FDL (short or long) attributed post-install via one of several techniques (fingerprint, copy unique).',
    )
    resolvedLink: Optional[str] = Field(
        None,
        description='The entire FDL, expanded from a short link. It is the same as the requested_link, if it is long. Parameters from this should not be used directly (ie: server can default utm_[campaign|medium|source] to a value when requested_link lack them, server determine the best fallback_link when requested_link specifies >1 fallback links).',
    )
    utmCampaign: Optional[str] = Field(
        None,
        description='Scion campaign value to be propagated by iSDK to Scion at post-install.',
    )
    utmContent: Optional[str] = Field(
        None,
        description='Scion content value to be propagated by iSDK to Scion at app-reopen.',
    )
    utmMedium: Optional[str] = Field(
        None,
        description='Scion medium value to be propagated by iSDK to Scion at post-install.',
    )
    utmSource: Optional[str] = Field(
        None,
        description='Scion source value to be propagated by iSDK to Scion at post-install.',
    )
    utmTerm: Optional[str] = Field(
        None,
        description='Scion term value to be propagated by iSDK to Scion at app-reopen.',
    )


class GetIosReopenAttributionRequest(BaseModel):
    bundleId: Optional[str] = Field(None, description='APP bundle ID.')
    requestedLink: Optional[str] = Field(
        None,
        description='FDL link to be verified from an app universal link open. The FDL link can be one of: 1) short FDL. e.g. .page.link/, or 2) long FDL. e.g. .page.link/?{query params}, or 3) Invite FDL. e.g. .page.link/i/',
    )
    sdkVersion: Optional[str] = Field(
        None,
        description='Google SDK version. Version takes the form "$major.$minor.$patch"',
    )


class GetIosReopenAttributionResponse(BaseModel):
    deepLink: Optional[str] = Field(
        None,
        description='The deep-link attributed the app universal link open. For both regular FDL links and invite FDL links.',
    )
    invitationId: Optional[str] = Field(
        None,
        description='Optional invitation ID, for only invite typed requested FDL links.',
    )
    iosMinAppVersion: Optional[str] = Field(
        None,
        description='FDL input value of the "&imv=" parameter, minimum app version to be returned to Google Firebase SDK running on iOS-9.',
    )
    resolvedLink: Optional[str] = Field(
        None,
        description='The entire FDL, expanded from a short link. It is the same as the requested_link, if it is long.',
    )
    utmCampaign: Optional[str] = Field(
        None,
        description='Scion campaign value to be propagated by iSDK to Scion at app-reopen.',
    )
    utmContent: Optional[str] = Field(
        None,
        description='Scion content value to be propagated by iSDK to Scion at app-reopen.',
    )
    utmMedium: Optional[str] = Field(
        None,
        description='Scion medium value to be propagated by iSDK to Scion at app-reopen.',
    )
    utmSource: Optional[str] = Field(
        None,
        description='Scion source value to be propagated by iSDK to Scion at app-reopen.',
    )
    utmTerm: Optional[str] = Field(
        None,
        description='Scion term value to be propagated by iSDK to Scion at app-reopen.',
    )


class GooglePlayAnalytics(BaseModel):
    gclid: Optional[str] = Field(
        None, description='Deprecated; FDL SDK does not process nor log it.'
    )
    utmCampaign: Optional[str] = Field(
        None,
        description='Campaign name; used for keyword analysis to identify a specific product promotion or strategic campaign.',
    )
    utmContent: Optional[str] = Field(
        None,
        description='Campaign content; used for A/B testing and content-targeted ads to differentiate ads or links that point to the same URL.',
    )
    utmMedium: Optional[str] = Field(
        None,
        description='Campaign medium; used to identify a medium such as email or cost-per-click.',
    )
    utmSource: Optional[str] = Field(
        None,
        description='Campaign source; used to identify a search engine, newsletter, or other source.',
    )
    utmTerm: Optional[str] = Field(
        None,
        description='Campaign term; used with paid search to supply the keywords for ads.',
    )


class ITunesConnectAnalytics(BaseModel):
    at: Optional[str] = Field(
        None, description='Affiliate token used to create affiliate-coded links.'
    )
    ct: Optional[str] = Field(
        None,
        description='Campaign text that developers can optionally add to any link in order to track sales from a specific marketing campaign.',
    )
    mt: Optional[str] = Field(
        None,
        description='iTune media types, including music, podcasts, audiobooks and so on.',
    )
    pt: Optional[str] = Field(
        None,
        description='Provider token that enables analytics for Dynamic Links from within iTunes Connect.',
    )


class IosInfo(BaseModel):
    iosAppStoreId: Optional[str] = Field(None, description='iOS App Store ID.')
    iosBundleId: Optional[str] = Field(None, description='iOS bundle ID of the app.')
    iosCustomScheme: Optional[str] = Field(
        None,
        description='Custom (destination) scheme to use for iOS. By default, we’ll use the bundle ID as the custom scheme. Developer can override this behavior using this param.',
    )
    iosFallbackLink: Optional[str] = Field(
        None, description='Link to open on iOS if the app is not installed.'
    )
    iosIpadBundleId: Optional[str] = Field(
        None, description='iPad bundle ID of the app.'
    )
    iosIpadFallbackLink: Optional[str] = Field(
        None,
        description='If specified, this overrides the ios_fallback_link value on iPads.',
    )
    iosMinimumVersion: Optional[str] = Field(None, description='iOS minimum version.')


class FlaggedAttributeEnum(Enum):
    UNSPECIFIED_ATTRIBUTE = 'UNSPECIFIED_ATTRIBUTE'
    SPAM = 'SPAM'


class Visibility(Enum):
    UNSPECIFIED_VISIBILITY = 'UNSPECIFIED_VISIBILITY'
    UNARCHIVED = 'UNARCHIVED'
    ARCHIVED = 'ARCHIVED'
    NEVER_SHOWN = 'NEVER_SHOWN'


class NavigationInfo(BaseModel):
    enableForcedRedirect: Optional[bool] = Field(
        None,
        description='If this option is on, FDL click will be forced to redirect rather than show an interstitial page.',
    )


class SocialMetaTagInfo(BaseModel):
    socialDescription: Optional[str] = Field(
        None, description='A short description of the link. Optional.'
    )
    socialImageLink: Optional[str] = Field(
        None, description='An image url string. Optional.'
    )
    socialTitle: Optional[str] = Field(
        None, description='Title to be displayed. Optional.'
    )


class Option(Enum):
    OPTION_UNSPECIFIED = 'OPTION_UNSPECIFIED'
    UNGUESSABLE = 'UNGUESSABLE'
    SHORT = 'SHORT'
    CUSTOM = 'CUSTOM'


class Suffix(BaseModel):
    customSuffix: Optional[str] = Field(
        None, description='Only applies to Option.CUSTOM.'
    )
    option: Optional[Option] = Field(None, description='Suffix option.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AnalyticsInfo(BaseModel):
    googlePlayAnalytics: Optional[GooglePlayAnalytics] = Field(
        None, description='Google Play Campaign Measurements.'
    )
    itunesConnectAnalytics: Optional[ITunesConnectAnalytics] = Field(
        None, description='iTunes Connect App Analytics.'
    )


class CreateShortDynamicLinkResponse(BaseModel):
    previewLink: Optional[str] = Field(
        None, description='Preview link to show the link flow chart. (debug info.)'
    )
    shortLink: Optional[str] = Field(
        None, description='Short Dynamic Link value. e.g. https://abcd.app.goo.gl/wxyz'
    )
    warning: Optional[List[DynamicLinkWarning]] = Field(
        None, description='Information about potential warnings on link creation.'
    )


class DynamicLinkInfo(BaseModel):
    analyticsInfo: Optional[AnalyticsInfo] = Field(
        None,
        description='Parameters used for tracking. See all tracking parameters in the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually).',
    )
    androidInfo: Optional[AndroidInfo] = Field(
        None,
        description='Android related information. See Android related parameters in the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually).',
    )
    desktopInfo: Optional[DesktopInfo] = Field(
        None,
        description='Desktop related information. See desktop related parameters in the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually).',
    )
    domainUriPrefix: Optional[str] = Field(
        None,
        description='E.g. https://maps.app.goo.gl, https://maps.page.link, https://g.co/maps More examples can be found in description of getNormalizedUriPrefix in j/c/g/firebase/dynamiclinks/uri/DdlDomain.java Will fallback to dynamic_link_domain is this field is missing',
    )
    dynamicLinkDomain: Optional[str] = Field(
        None,
        description='Dynamic Links domain that the project owns, e.g. abcd.app.goo.gl [Learn more](https://firebase.google.com/docs/dynamic-links/android/receive) on how to set up Dynamic Link domain associated with your Firebase project. Required if missing domain_uri_prefix.',
    )
    iosInfo: Optional[IosInfo] = Field(
        None,
        description='iOS related information. See iOS related parameters in the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually).',
    )
    link: Optional[str] = Field(
        None,
        description="The link your app will open, You can specify any URL your app can handle. This link must be a well-formatted URL, be properly URL-encoded, and use the HTTP or HTTPS scheme. See 'link' parameters in the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually). Required.",
    )
    navigationInfo: Optional[NavigationInfo] = Field(
        None,
        description='Information of navigation behavior of a Firebase Dynamic Links.',
    )
    socialMetaTagInfo: Optional[SocialMetaTagInfo] = Field(
        None,
        description='Parameters for social meta tag params. Used to set meta tag data for link previews on social sites.',
    )


class ManagedShortLink(BaseModel):
    creationTime: Optional[str] = Field(
        None, description='Creation timestamp of the short link.'
    )
    flaggedAttribute: Optional[List[FlaggedAttributeEnum]] = Field(
        None, description='Attributes that have been flagged about this short url.'
    )
    info: Optional[DynamicLinkInfo] = Field(None, description='Full Dyamic Link info')
    link: Optional[str] = Field(
        None,
        description='Short durable link url, for example, "https://sample.app.goo.gl/xyz123". Required.',
    )
    linkName: Optional[str] = Field(
        None, description='Link name defined by the creator. Required.'
    )
    visibility: Optional[Visibility] = Field(
        None, description='Visibility status of link.'
    )


class CreateManagedShortLinkRequest(BaseModel):
    dynamicLinkInfo: Optional[DynamicLinkInfo] = Field(
        None,
        description='Information about the Dynamic Link to be shortened. [Learn more](https://firebase.google.com/docs/reference/dynamic-links/link-shortener).',
    )
    longDynamicLink: Optional[str] = Field(
        None,
        description='Full long Dynamic Link URL with desired query parameters specified. For example, "https://sample.app.goo.gl/?link=http://www.google.com&apn=com.sample", [Learn more](https://firebase.google.com/docs/reference/dynamic-links/link-shortener).',
    )
    name: Optional[str] = Field(
        None,
        description="Link name to associate with the link. It's used for marketer to identify manually-created links in the Firebase console (https://console.firebase.google.com/). Links must be named to be tracked.",
    )
    sdkVersion: Optional[str] = Field(
        None,
        description='Google SDK version. Version takes the form "$major.$minor.$patch"',
    )
    suffix: Optional[Suffix] = Field(
        None, description='Short Dynamic Link suffix. Optional.'
    )


class CreateManagedShortLinkResponse(BaseModel):
    managedShortLink: Optional[ManagedShortLink] = Field(
        None, description='Short Dynamic Link value. e.g. https://abcd.app.goo.gl/wxyz'
    )
    previewLink: Optional[str] = Field(
        None, description='Preview link to show the link flow chart. (debug info.)'
    )
    warning: Optional[List[DynamicLinkWarning]] = Field(
        None, description='Information about potential warnings on link creation.'
    )


class CreateShortDynamicLinkRequest(BaseModel):
    dynamicLinkInfo: Optional[DynamicLinkInfo] = Field(
        None,
        description='Information about the Dynamic Link to be shortened. [Learn more](https://firebase.google.com/docs/reference/dynamic-links/link-shortener).',
    )
    longDynamicLink: Optional[str] = Field(
        None,
        description='Full long Dynamic Link URL with desired query parameters specified. For example, "https://sample.app.goo.gl/?link=http://www.google.com&apn=com.sample", [Learn more](https://firebase.google.com/docs/reference/dynamic-links/link-shortener).',
    )
    sdkVersion: Optional[str] = Field(
        None,
        description='Google SDK version. Version takes the form "$major.$minor.$patch"',
    )
    suffix: Optional[Suffix] = Field(
        None, description='Short Dynamic Link suffix. Optional.'
    )
